PUT https://webcomp.bsu.ru/api/finals25/reservation/authorized/add HTTP/1.1
content-type: application/json
Authorization: Bearer 5039|SioMDq91ZGZElaGIVMUcP5vExeeDMXW3mxvTOv6y

{"email":"Ууperorc@bsu.ru","phone":"421665","guests":10,"reservation_date":"2025-04-01 11:10:00"}