PUT https://webcomp.bsu.ru/api/finals25/reservation/public/add HTTP/1.1
content-type: application/json

{"email":"superelf@bsu.ru","phone":"421665","guests":20,"reservation_date":"2025-04-02 12:10:00"}